// Code generated by mockery v1.0.0. DO NOT EDIT.

package backendmocks

import mock "github.com/stretchr/testify/mock"

// Backend is an autogenerated mock type for the Backend type
type Backend struct {
	mock.Mock
}
