// Code generated by mockery v1.0.0. DO NOT EDIT.

package slackmocks

import context "context"
import mock "github.com/stretchr/testify/mock"

import slack "github.com/nlopes/slack"

// Slack is an autogenerated mock type for the Slack type
type Slack struct {
	mock.Mock
}

// PostMessageContext provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Slack) PostMessageContext(_a0 context.Context, _a1 string, _a2 string, _a3 slack.PostMessageParameters) (string, string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, slack.PostMessageParameters) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, string, slack.PostMessageParameters) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, slack.PostMessageParameters) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
